"""
Gate experiment: does plain FLIP even work on dog -> cat?

WHY A GATE
----------
Every result so far uses truck -> deer, a pair whose stealthy flip pool is
exactly zero (scripts/adaptive/pair_analysis.py). The constrained attacker there
had no legal move, so its collapse says little about the defense. dog -> cat has
a pool of 265, making it the pair where a stealthy attack is possible at all.

But FLIP was never published on dog -> cat. Before spending weeks on an adaptive
study there, confirm the *unconstrained* attack installs a backdoor. If it does
not, there is nothing for a defense to defend and the pair is a dead end -- a
cheap answer to a question that would otherwise be discovered late.

THE FLOOR MATTERS MORE HERE THAN IT DID BEFORE
----------------------------------------------
PTA counts triggered source-class test images classified as the target. For
truck -> deer a clean model almost never does this, so the floor was 0.001 and
any PTA above ~0.01 meant a real backdoor. Dogs and cats are genuinely confusable,
so a clean model misclassifies some dogs as cats with no attack at all. The floor
could be 0.05-0.15, and reading raw PTA without it would badly overstate the
attack. This script therefore always trains the clean-label control on the same
pair and reports the *lift* over that floor.

STAGES AND RESUME
-----------------
    1. dogcat_1_expert        train the triggered expert, record trajectory
    2. dogcat_2_labels        optimise the poisoned labels (the slow stage)
    3. dogcat_3_flips         rank by margin, write label tensors
    4. dogcat_flip_none       victim on FLIP labels   -> PTA_attack
    5. dogcat_cleanlabel_none victim on true labels   -> PTA_floor
    6. gate decision from (PTA_attack - PTA_floor)

Every stage is checked against its own output files, so an interrupted run
resumes at the stage that did not finish and never repeats a completed one.
This is why the attack is three experiments rather than one config: a crash
during label optimisation must not force the expert to be retrained.

Resume is stage-level, not epoch-level. A stage killed midway restarts from its
own beginning, because the FLIP trainer has no resume-from-checkpoint path and
adding one would mean changing code every existing experiment depends on. Worst
case you lose the stage in progress, not the pipeline.

Usage:
    python scripts/adaptive/run_dogcat_gate.py
    python scripts/adaptive/run_dogcat_gate.py --dry-run     # show plan only
    python scripts/adaptive/run_dogcat_gate.py --force       # redo everything
"""

import argparse
import functools
import json
import subprocess
import sys
import time
from pathlib import Path

print = functools.partial(print, flush=True)  # noqa: A001


VICTIM_TEMPLATE = """# Auto-generated by scripts/adaptive/run_dogcat_gate.py
# {comment}
#
# Run:
#   python run_experiment.py {experiment_name}

[train_user_defense]
input_labels = "{input_labels}"
true_labels  = "{true_labels}"
output_dir   = "experiments/{experiment_name}/"
user_model   = "{user_model}"
trainer      = "{trainer}"
dataset      = "{dataset}"
source_label = {source_label}
target_label = {target_label}
poisoner     = "{poisoner}"
defense_mode = "none"
soft         = false
alpha        = 0.0
seed         = {seed}

[train_user_defense.knn]
encoder       = "{encoder}"
k             = {k}
scoring       = "disagreement"
removal_count = "auto"
threshold     = 0.5
batch_size    = 256
feature_cache = "data/ssl_features"
"""


def run_stage(root: Path, name: str, python: str) -> bool:
    print(f"\n{'=' * 70}\n[gate] {name}\n{'=' * 70}")
    started = time.time()
    proc = subprocess.run([python, "run_experiment.py", name], cwd=root)
    mins = (time.time() - started) / 60
    ok = proc.returncode == 0
    print(f"[gate] {'done' if ok else 'FAILED'} ({mins:.1f} min): {name}")
    return ok


def attack_stages(root: Path, attack_dir: Path, budget: int, epochs: int):
    """(experiment name, human label, is-it-already-done) for each attack stage.

    Each predicate names the concrete artefact that proves the stage finished,
    so a half-written stage is never mistaken for a complete one. The expert
    check looks for the FINAL epoch specifically: a run killed at epoch 15
    leaves plenty of checkpoints behind, and counting files would wrongly skip
    it.
    """
    ckpt_dir = root / "out" / "checkpoints" / "r32p_1xs_dogcat" / "0"
    return [
        ("dogcat_1_expert", "train expert trajectory",
         lambda: any(ckpt_dir.glob(f"model_{epochs}_*.pth"))),
        ("dogcat_2_labels", "optimise poisoned labels",
         lambda: (root / attack_dir / "labels.npy").exists()
         and (root / attack_dir / "true.npy").exists()),
        ("dogcat_3_flips", "select flips per budget",
         lambda: (root / attack_dir / f"{budget}.npy").exists()),
    ]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--attack-dir", default="experiments/dogcat_attack")
    p.add_argument("--expert-epochs", type=int, default=20,
                   help="Must match [train_expert].epochs in "
                        "experiments/dogcat_1_expert/config.toml.")
    p.add_argument("--budget", type=int, default=1500)
    p.add_argument("--source-label", type=int, default=5)   # dog
    p.add_argument("--target-label", type=int, default=3)   # cat
    p.add_argument("--dataset", default="cifar")
    p.add_argument("--user-model", default="r32p")
    p.add_argument("--trainer", default="sgd")
    p.add_argument("--poisoner", default="1xs")
    p.add_argument("--encoder", default="dinov2_vits14")
    p.add_argument("--k", type=int, default=20)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--lift-threshold", type=float, default=0.30,
                   help="Minimum PTA lift over the clean-label floor for the "
                        "pair to be worth an adaptive study.")
    p.add_argument("--python", default=sys.executable)
    p.add_argument("--force", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    root = Path(__file__).resolve().parents[2]
    attack_dir = Path(args.attack_dir)
    labels_path = f"{attack_dir.as_posix()}/{args.budget}.npy"
    true_path = f"{attack_dir.as_posix()}/true.npy"

    common = dict(
        user_model=args.user_model, trainer=args.trainer, dataset=args.dataset,
        source_label=args.source_label, target_label=args.target_label,
        poisoner=args.poisoner, encoder=args.encoder, k=args.k, seed=args.seed,
    )
    victims = [
        ("dogcat_flip_none",
         f"Plain FLIP on dog->cat, budget {args.budget}, no defense. "
         f"This is the gate: does the attack work at all?",
         dict(common, input_labels=labels_path, true_labels=true_path)),
        ("dogcat_cleanlabel_none",
         "Clean-label control on dog->cat: no attack, no defense. "
         "Dogs and cats are confusable, so this floor is expected to be well "
         "above the truck->deer floor of 0.001.",
         dict(common, input_labels=true_path, true_labels=true_path)),
    ]

    (root / attack_dir).mkdir(parents=True, exist_ok=True)

    # Build the full plan first so an interrupted run shows exactly where it
    # will pick up before it commits to hours of compute.
    plan = []
    for name, label, done_fn in attack_stages(
            root, attack_dir, args.budget, args.expert_epochs):
        plan.append((name, label, done_fn() and not args.force))

    for name, comment, fields in victims:
        exp = root / "experiments" / name
        exp.mkdir(parents=True, exist_ok=True)
        (exp / "config.toml").write_text(
            VICTIM_TEMPLATE.format(experiment_name=name, comment=comment,
                                   **fields))
        label = ("victim: FLIP labels, no defense"
                 if "flip" in name else "victim: clean labels, no defense")
        plan.append((name, label,
                     (exp / "summary.json").exists() and not args.force))

    print(f"\n[gate] plan ({sum(1 for _, _, d in plan if not d)} of "
          f"{len(plan)} stages to run)\n")
    for i, (name, label, done) in enumerate(plan, 1):
        print(f"  {i}. [{'done   ' if done else 'PENDING'}] {label}")
        print(f"       {name}")

    if args.dry_run:
        print("\n[gate] dry run: configs written, nothing trained")
        return

    for name, label, done in plan:
        if done:
            print(f"\n[gate] skipping finished stage: {name}")
            continue
        if not run_stage(root, name, args.python):
            sys.exit(
                f"\n[gate] stage failed: {name}\n"
                f"[gate] rerun the same command - finished stages are skipped."
            )

    # --- decision ---
    def summary(name):
        path = root / "experiments" / name / "summary.json"
        return json.loads(path.read_text()) if path.exists() else None

    atk, clean = summary("dogcat_flip_none"), summary("dogcat_cleanlabel_none")
    if not (atk and clean):
        sys.exit("[gate] missing summaries; cannot decide")

    lift = atk["pta"] - clean["pta"]
    print(f"\n{'=' * 70}\nGATE DECISION  (dog -> cat)\n{'=' * 70}")
    print(f"  PTA, plain FLIP        {atk['pta']:.4f}")
    print(f"  PTA, clean-label floor {clean['pta']:.4f}")
    print(f"  lift over floor        {lift:.4f}   "
          f"(threshold {args.lift_threshold})")
    print(f"  CTA, plain FLIP        {atk['cta']:.4f}")
    print(f"  CTA, clean ceiling     {clean['cta']:.4f}   "
          f"(attack costs {clean['cta'] - atk['cta']:.4f})")

    if lift >= args.lift_threshold:
        print("\n  PASS - the backdoor installs on this pair.")
        print("  Next: run the adaptive sweep here. Point")
        print("  modules/select_flips_adaptive at experiments/dogcat_attack,")
        print("  then run_adaptive_sweep.py with --source-label 5.")
        print("  This is the setting that decides whether the audit has a")
        print("  real failure mode or is universal.")
    else:
        print("\n  FAIL - no usable backdoor on this pair.")
        print("  Do NOT run the adaptive study here: a defense cannot be")
        print("  credited or blamed for an attack that does not work. Report")
        print("  this as a finding - FLIP itself is pair-dependent - and let")
        print("  the pair-stealth map carry the paper.")

    (root / args.attack_dir / "gate_decision.json").write_text(json.dumps({
        "pair": f"{args.source_label}->{args.target_label}",
        "budget": args.budget,
        "pta_attack": atk["pta"], "pta_floor": clean["pta"], "lift": lift,
        "cta_attack": atk["cta"], "cta_clean": clean["cta"],
        "lift_threshold": args.lift_threshold,
        "passed": bool(lift >= args.lift_threshold),
    }, indent=2))
    print(f"\n  written: {args.attack_dir}/gate_decision.json")


if __name__ == "__main__":
    main()
