"""
Train victim models across the adaptive attacker's stealth-vs-efficacy frontier.

Prerequisite:
    python run_experiment.py adaptive_flip_cifar_1xs

For each stealth budget tau this generates and runs two victim trainings:

    adaptive_<...>_tau<tau>_none     no defense  -> does the stealthy attack
                                                    still install a backdoor?
    adaptive_<...>_tau<tau>_remove   k-NN audit  -> does the audit still stop
                                                    an attacker who knows it?

It also runs MATCHED-BUDGET CONTROLS: vanilla (defense-unaware) FLIP at the
reduced budgets the constrained attacker is forced down to. Without these the
frontier is uninterpretable — an ASR drop at tau = 0.5 could mean either
"stealth costs attack quality" or merely "260 flips is fewer than 1500". The
controls separate the two. Vanilla labels at budgets 150/300/500/1000 already
exist in experiments/example_attack, so the controls cost nothing extra to set
up.

Runs are skipped when summary.json already exists, so the sweep is resumable;
pass --force to retrain.

Usage:
    python scripts/adaptive/run_adaptive_sweep.py
    python scripts/adaptive/run_adaptive_sweep.py --taus 1.0 0.7 0.5 --dry-run
    python scripts/adaptive/run_adaptive_sweep.py --modes remove --force
"""

import argparse
import functools
import json
import subprocess
import sys
import time
from pathlib import Path


# Progress lines are the only way to follow a multi-hour sweep from a redirected
# log. Python block-buffers stdout when it is not a TTY, so without flushing
# these sit in the buffer for hours while the child processes' output streams
# past them.
print = functools.partial(print, flush=True)  # noqa: A001


CONFIG_TEMPLATE = """# Auto-generated by scripts/adaptive/run_adaptive_sweep.py
# {comment}
#
# Run:
#   python run_experiment.py {experiment_name}

[train_user_defense]
input_labels = "{input_labels}"
true_labels  = "{true_labels}"
output_dir   = "experiments/{experiment_name}/"
user_model   = "{user_model}"
trainer      = "{trainer}"
dataset      = "{dataset}"
source_label = {source_label}
target_label = {target_label}
poisoner     = "{poisoner}"
defense_mode = "{mode}"
soft         = false
alpha        = 0.0
seed         = {seed}

[train_user_defense.knn]
encoder       = "{encoder}"
k             = {k}
scoring       = "disagreement"
removal_count = "auto"
threshold     = {threshold}
batch_size    = 256
feature_cache = "data/ssl_features"
"""


def tau_slug(tau: float) -> str:
    """Filesystem-safe tau label: 0.5 -> '0p500'."""
    return f"{tau:.3f}".replace(".", "p")


def write_config(root: Path, name: str, comment: str, **fields) -> Path:
    exp_dir = root / "experiments" / name
    exp_dir.mkdir(parents=True, exist_ok=True)
    path = exp_dir / "config.toml"
    path.write_text(
        CONFIG_TEMPLATE.format(experiment_name=name, comment=comment, **fields)
    )
    return path


def plan_runs(root: Path, args) -> list:
    """Build the full (name, comment, fields) work list."""
    attack_dir = Path(args.attack_dir)
    manifest_path = root / attack_dir / "manifest.json"
    if not manifest_path.exists():
        sys.exit(
            f"Attack manifest not found: {manifest_path}\n"
            f"Run `python run_experiment.py adaptive_flip_cifar_1xs` first."
        )
    manifest = json.loads(manifest_path.read_text())

    # tau -> number of flips the constrained attacker could actually place.
    selected_by_tau = {
        r["tau"]: r["n_selected"]
        for r in manifest["runs"] if r["budget"] == args.budget
    }

    common = dict(
        user_model=args.user_model,
        trainer=args.trainer,
        dataset=args.dataset,
        source_label=args.source_label,
        target_label=args.target_label,
        poisoner=args.poisoner,
        encoder=args.encoder,
        k=args.k,
        threshold=args.threshold,
        seed=args.seed,
    )

    # Mode-major ordering: every 'none' run first. If the sweep is interrupted,
    # a complete undefended curve is far more informative than a half-finished
    # interleaving, and the 'remove' runs only matter for taus where the
    # undefended attack actually worked.
    runs = []
    for mode in args.modes:
        for tau in args.taus:
            if tau not in selected_by_tau:
                print(f"[warn] tau={tau} absent from manifest; skipping")
                continue
            n_sel = selected_by_tau[tau]
            labels = f"{attack_dir.as_posix()}/tau_{tau:.3f}/{args.budget}.npy"
            runs.append((
                f"{args.name_prefix}_tau{tau_slug(tau)}_{mode}",
                f"Adaptive FLIP, stealth budget tau={tau} "
                f"({n_sel} flips placed), defense_mode={mode}",
                dict(common, input_labels=labels,
                     true_labels=f"{attack_dir.as_posix()}/true.npy",
                     mode=mode),
            ))

    # Clean-label floor: train on the true labels, no attack at all. Without it
    # "PTA dropped to 0.002" is uninterpretable — a clean model already
    # classifies some triggered source images as the target class, and that
    # residual is the floor any defended PTA should be compared against.
    if not args.skip_clean_control:
        runs.append((
            args.clean_control_name,
            "Clean-label control: no attack, no defense. Establishes the CTA "
            "ceiling and the PTA floor every other row is measured against.",
            dict(common,
                 input_labels=f"{attack_dir.as_posix()}/true.npy",
                 true_labels=f"{attack_dir.as_posix()}/true.npy",
                 mode="none"),
        ))

    # Matched-budget controls: vanilla FLIP at the budgets tau forces.
    if not args.skip_controls:
        for n in args.control_budgets:
            src = root / args.control_label_dir / f"{n}.npy"
            if not src.exists():
                print(f"[warn] control labels missing: {src}; skipping n={n}")
                continue
            runs.append((
                f"{args.control_prefix}_n{n}_none",
                f"Matched-budget control: defense-unaware FLIP at budget {n}, "
                f"no defense. Isolates flip COUNT from flip QUALITY.",
                dict(common,
                     input_labels=f"{Path(args.control_label_dir).as_posix()}/{n}.npy",
                     true_labels=f"{Path(args.control_label_dir).as_posix()}/true.npy",
                     mode="none"),
            ))

    return runs


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--taus", type=float, nargs="+",
                   default=[1.0, 0.9, 0.8, 0.7, 0.6, 0.5])
    p.add_argument("--modes", nargs="+", choices=["none", "remove"],
                   default=["none", "remove"])
    p.add_argument("--budget", type=int, default=1500)
    p.add_argument("--attack-dir", default="experiments/adaptive_flip_cifar_1xs")
    p.add_argument("--control-label-dir", default="experiments/example_attack")
    p.add_argument("--control-budgets", type=int, nargs="+",
                   default=[150, 300, 500, 1000])
    p.add_argument("--skip-controls", action="store_true")
    p.add_argument("--skip-clean-control", action="store_true")
    p.add_argument("--clean-control-name", default="cleanlabel_cifar_1xs_none")
    p.add_argument("--name-prefix", default="adaptive_cifar_1xs")
    p.add_argument("--control-prefix", default="flipbudget_cifar_1xs")
    p.add_argument("--dataset", default="cifar")
    p.add_argument("--user-model", default="r32p")
    p.add_argument("--trainer", default="sgd")
    p.add_argument("--poisoner", default="1xs")
    p.add_argument("--source-label", type=int, default=9)
    p.add_argument("--target-label", type=int, default=4)
    p.add_argument("--encoder", default="dinov2_vits14")
    p.add_argument("--k", type=int, default=20)
    p.add_argument("--threshold", type=float, default=0.5)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--python", default=sys.executable)
    p.add_argument("--force", action="store_true",
                   help="Retrain even when summary.json already exists.")
    p.add_argument("--dry-run", action="store_true",
                   help="Write configs and print the plan; train nothing.")
    args = p.parse_args()

    root = Path(__file__).resolve().parents[2]
    runs = plan_runs(root, args)

    print(f"[sweep] {len(runs)} runs planned\n")
    pending = []
    for name, comment, fields in runs:
        write_config(root, name, comment, **fields)
        done = (root / "experiments" / name / "summary.json").exists()
        status = "done" if done and not args.force else "PENDING"
        print(f"  [{status:7}] {name}")
        if not done or args.force:
            pending.append(name)

    if args.dry_run:
        print(f"\n[sweep] dry run: {len(pending)} would train")
        return

    print(f"\n[sweep] training {len(pending)} runs "
          f"(~200 epochs each)\n")
    failures = []
    for i, name in enumerate(pending, 1):
        print(f"\n{'=' * 70}\n[sweep] ({i}/{len(pending)}) {name}\n{'=' * 70}")
        started = time.time()
        proc = subprocess.run(
            [args.python, "run_experiment.py", name], cwd=root,
        )
        mins = (time.time() - started) / 60
        if proc.returncode != 0:
            print(f"[sweep] FAILED ({mins:.1f} min): {name}")
            failures.append(name)
        else:
            print(f"[sweep] done ({mins:.1f} min): {name}")

    print(f"\n[sweep] complete: {len(pending) - len(failures)} succeeded, "
          f"{len(failures)} failed")
    for name in failures:
        print(f"  FAILED: {name}")
    if failures:
        sys.exit(1)
    print("\nNext: python scripts/adaptive/aggregate_frontier.py")


if __name__ == "__main__":
    main()
