"""
Generate per-k experiment configs for the Deep k-NN defense sweep.

For each k in --k-values, writes two configs under experiments/:
    knn_defense_cifar_<poisoner>_<budget>_none_k{k}/config.toml
    knn_defense_cifar_<poisoner>_<budget>_remove_k{k}/config.toml

These are drop-in replacements for the existing knn_defense_cifar_1xs_1500_{none,remove}
configs and can be executed via:
    python run_experiment.py <experiment_name>

The 'none' mode is regression-equivalent to vanilla train_user but still produces
KNN detection scores at the configured k. The 'remove' mode applies the auto-threshold
removal (score > threshold) before training.

Usage:
    python scripts/k_sweep/generate_config.py \
        --k-values 1 5 10 20 50 100 200 500 1000 2000 \
        --poisoner 1xs --budget 1500 --dataset cifar --seed 0
"""

import argparse
import os
from pathlib import Path


CONFIG_TEMPLATE = """# Auto-generated by scripts/k_sweep/generate_config.py
# Deep k-NN defense, k={k}, mode={mode}
#
# Run:
#   python run_experiment.py {experiment_name}

[train_user_defense]
input_labels = "precomputed_labels/{dataset}/{user_model}/{poisoner}/{budget}.npy"
true_labels  = "precomputed_labels/{dataset}/{user_model}/{poisoner}/true.npy"
output_dir   = "experiments/{experiment_name}/"
user_model   = "{user_model}"
trainer      = "{trainer}"
dataset      = "{dataset}"
source_label = {source_label}
target_label = {target_label}
poisoner     = "{poisoner}"
defense_mode = "{mode}"
soft         = false
alpha        = 0.0
seed         = {seed}

[train_user_defense.knn]
encoder       = "{encoder}"
k             = {k}
scoring       = "{scoring}"
removal_count = "{removal_count}"
threshold     = {threshold}
batch_size    = 256
feature_cache = "data/ssl_features"
"""


def write_config(
    project_root: Path,
    *,
    k: int,
    mode: str,
    dataset: str,
    user_model: str,
    trainer: str,
    poisoner: str,
    budget: int,
    source_label: int,
    target_label: int,
    encoder: str,
    scoring: str,
    removal_count: str,
    threshold: float,
    seed: int,
    name_prefix: str,
) -> str:
    experiment_name = f"{name_prefix}_{mode}_k{k}"
    exp_dir = project_root / "experiments" / experiment_name
    exp_dir.mkdir(parents=True, exist_ok=True)

    contents = CONFIG_TEMPLATE.format(
        k=k,
        mode=mode,
        experiment_name=experiment_name,
        dataset=dataset,
        user_model=user_model,
        trainer=trainer,
        poisoner=poisoner,
        budget=budget,
        source_label=source_label,
        target_label=target_label,
        encoder=encoder,
        scoring=scoring,
        removal_count=removal_count,
        threshold=threshold,
        seed=seed,
    )
    (exp_dir / "config.toml").write_text(contents)
    return experiment_name


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--k-values", type=int, nargs="+",
                   default=[1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000])
    p.add_argument("--modes", nargs="+", choices=["none", "remove"],
                   default=["none", "remove"])
    p.add_argument("--dataset", default="cifar")
    p.add_argument("--user-model", default="r32p")
    p.add_argument("--trainer", default="sgd")
    p.add_argument("--poisoner", default="1xs")
    p.add_argument("--budget", type=int, default=1500)
    p.add_argument("--source-label", type=int, default=9)
    p.add_argument("--target-label", type=int, default=4)
    p.add_argument("--encoder", default="dinov2_vits14")
    p.add_argument("--scoring", default="disagreement",
                   choices=["disagreement", "weighted_disagreement"])
    p.add_argument("--removal-count", default="auto")
    p.add_argument("--threshold", type=float, default=0.5)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--name-prefix", default=None,
                   help="Prefix for generated experiment names. "
                        "Defaults to knn_defense_<dataset>_<poisoner>_<budget>.")
    p.add_argument("--project-root", default=None,
                   help="Project root (defaults to two levels above this script).")
    return p.parse_args()


def main():
    args = parse_args()

    project_root = Path(args.project_root) if args.project_root else \
        Path(__file__).resolve().parents[2]

    name_prefix = args.name_prefix or \
        f"knn_defense_{args.dataset}_{args.poisoner}_{args.budget}"

    generated = []
    for k in args.k_values:
        for mode in args.modes:
            name = write_config(
                project_root,
                k=k,
                mode=mode,
                dataset=args.dataset,
                user_model=args.user_model,
                trainer=args.trainer,
                poisoner=args.poisoner,
                budget=args.budget,
                source_label=args.source_label,
                target_label=args.target_label,
                encoder=args.encoder,
                scoring=args.scoring,
                removal_count=args.removal_count,
                threshold=args.threshold,
                seed=args.seed,
                name_prefix=name_prefix,
            )
            generated.append(name)
            print(f"[generate_config] wrote experiments/{name}/config.toml")

    # Print a newline-separated list of experiment names so shell scripts can
    # capture them with `mapfile -t < <(python generate_config.py --list-only)`.
    if os.environ.get("KSWEEP_EMIT_LIST") == "1":
        print("---NAMES---")
        for name in generated:
            print(name)


if __name__ == "__main__":
    main()
